# Generated by Django 6.0.3 on 2026-03-29 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='workouts',
            name='exercises',
            field=models.ManyToManyField(through='workouts.WorkoutsExercises', to='workouts.exercises'),
        ),
        migrations.AlterField(
            model_name='workoutsexercises',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.exercises'),
        ),
        migrations.DeleteModel(
            name='Exercise',
        ),
    ]
